"""empty message

Revision ID: 15d9c87b995c
Revises: 645b1cd238f7
Create Date: 2022-09-03 14:07:38.503835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15d9c87b995c'
down_revision = '645b1cd238f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'firstname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firstname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('lastname', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
